In [1]:
1.#Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np

In [2]:
list = [0,1,2,3,4,5]
arr = np.array(list)

In [3]:
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
print(arr.dtype)

int64


In [6]:
2.#Given a NumPy array 'arr', check if its data types is float64.
arr = np.array([1.5,2.6,3.7])

In [7]:
arr

array([1.5, 2.6, 3.7])

In [8]:
print(arr.dtype)

float64


In [3]:
3.#Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
import numpy as np
complex_arr = np.array([2+3j,5-4j,0.4+7j],dtype= np.complex128)
print(complex_arr)

[2. +3.j 5. -4.j 0.4+7.j]


In [4]:
print(complex_arr.dtype)

complex128


In [14]:
4.#Convert an existing NumPy array 'arr'of integers to float32 data type.
import numpy as np
array1= np.array([1,2,3,4,5])
array1 = array1.astype(np.float32)
print (type(array1[0]))

<class 'numpy.float32'>


In [20]:
5.#Given a NumPy array 'arr'with float64 data type,convert it to float32 to reduce decimal precision.
import numpy as np
arr = np.ones(4,dtype="float64")
print("Original array:\n",arr,"\n")
print("type of original array:\n",arr.dtype,"\n")
arr = np.float32(arr)
print("type of modified array:\n",arr.dtype,"\n")


Original array:
 [1. 1. 1. 1.] 

type of original array:
 float64 

type of modified array:
 float32 



In [2]:
6.#Write a function array_attributes that takes a numpy array as input and return its shape,size and data type.
import numpy as np
array1 = np.array([[1,2,3,4],[5,6,7,8]])
print(array1.shape)

(2, 4)


In [3]:
print(array1.size)

8


In [4]:
print(array1.dtype)

int64


In [11]:
7.#Write a function array_dimension that takes a numpy array as input and return its dimensionality.
var = np.array([[3,5,6],[7,1,9]])
print(np.ndim(var))

2


In [13]:
8.#Design a function item_size_info that takes a numpy array as input and return the item size and the total size in bytes.
x = np.array([50,60,80])
print("size of the array:",x.size)
print("item size of one array element in bytes:",x.itemsize)
print("total size of numpy array in bytes:",x.size * x.itemsize)

size of the array: 3
item size of one array element in bytes: 8
total size of numpy array in bytes: 24


In [8]:
11.#Create a function 'create_zeros_array' that takes an integer 'n' as input and returns a numpy array of zeros with n elements.
import numpy as np
create_zeros_array = np.zeros(6)

In [9]:
create_zeros_array

array([0., 0., 0., 0., 0., 0.])

In [30]:
12.#Create a function 'create_ones_matrix' that takes an integer 'rows' and 'cols' as inputs and generates a 2D numpy array filled with ones of size 'rows x cols'.
def create_ones_matrix(rows,cols):
    matrix = np.ones((2,2))
    return matrix

In [31]:
print(create_ones_matrix(2,2))

[[1. 1.]
 [1. 1.]]


In [32]:
13.#Write a function 'generate_range_array' that takes three integers atart,stop and step as arguments and creates a numpy array with a range starting from 'start',ending at stop and with the specified step.
import numpy as np
generate_range_array = np.arange(1,10,3)

In [33]:
generate_range_array

array([1, 4, 7])

In [36]:
14.#Design a function 'generate_linear_space'that takes two floats 'start','stop',and an integer 'num' as arguments and generate a numpy array with num equally spaced between start and stop(inclusive). 
generate_linear_space = np.linspace(start=2.5,stop=8.5, num = 4)

In [37]:
generate_linear_space

array([2.5, 4.5, 6.5, 8.5])

In [53]:
15.#Create a function 'create_identity_matrix' that takes an integer 'n' as input and generates a square identity matrix of size 'n x n' using 'numpy.eye'.
import numpy as np
Identity_matrix = np.eye(2, dtype=int)

In [54]:
Identity_matrix

array([[1, 0],
       [0, 1]])

In [55]:
16.#Write a function that takes a python list and converts it into a numpy array.
list = [1,2,3,4,5]
arr = np.array(list)

In [56]:
arr

array([1, 2, 3, 4, 5])

In [3]:
17.#Create a numpy array and demonstrate the use of 'numpy.view' to create a new array object with the same data.
import numpy as np
x = np.array([3,4,5])
y = np.empty(1,dtype = object)
y[:]= [x]
print(id(x))
print(id(y[0]))

131806309124112
131806309124112


In [1]:
18.#Write a function that takes two numpy arrays and concatenates them along a specified axis.
import numpy as np
a = np.array([2,3,4])
b = np.array([5,6,7])
result = np.concatenate((a,b), axis = 0)

In [2]:
result

array([2, 3, 4, 5, 6, 7])

In [4]:
19.#Create two numpy arrays with different shapes and concatenate them horizontally using 'numpy.concatenate'.  
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[4,7],[3,8]])
numpy_concatenate = np.hstack((arr1,arr2))

In [5]:
numpy_concatenate

array([[1, 2, 3, 4, 7],
       [4, 5, 6, 3, 8]])

In [6]:
20.#Write a function that vertically stacks multiple numpy arrays given as a list.
a = np.array([[3,4,5],[5,6,7],[4,5,1]])
b = np.array([[6,7,8],[2,4,8],[1,9,5]])
c = np.array([[5,6,7],[3,4,1],[6,7,9]])
result = np.vstack((a,b,c))

In [7]:
result

array([[3, 4, 5],
       [5, 6, 7],
       [4, 5, 1],
       [6, 7, 8],
       [2, 4, 8],
       [1, 9, 5],
       [5, 6, 7],
       [3, 4, 1],
       [6, 7, 9]])

In [8]:
21.#Write a python function using numpy to create an array of integers within specified range(inclusive) with a given step size.
import numpy as np
array = np.arange(20,45)

In [9]:
array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44])

In [10]:
22.#Write a python function using numpy to generate an array of 10 equally spaced values between 0 an 1(incusive).
array = np.linspace(0,1,10)

In [11]:
array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
23.#Write a python function using numpy to create an array of 5 logarithmically spaces values between 0 and 1000(inclusive).
arr = np.logspace(1,1000,num = 5)

/opt/conda/lib/python3.10/site-packages/numpy/core/function_base.py:277: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


In [13]:
arr

array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [44]:
24.#Create a pandas DataFrame using a numpy array that contains 5 rows and 2 columns,where the  values are random integers between 1 and 100.
import numpy as np
import pandas as pd
data = np.random.randint(1,100, size =(5,3))
df = pd.DataFrame(data,columns=['random_no_1', 'random_no_2', 'random_no_3'])
print(df)

   random_no_1  random_no_2  random_no_3
0           93            4           52
1            3           22           93
2           71           75           59
3            7           97           35
4            5           79            9


In [15]:
25.#Write a function that takes a DataFrame and replace all negative values in a specific column with zeros.Use numpy operations within tha pandas DataFrame.
import pandas as pd
df = pd.DataFrame({"A":[1,2,-3,4],
                   "B":[-5,3,7,-8],
                   "C":[2,-6,-1,9]})

In [16]:
df

A  B  C
0  1 -5  2
1  2  3 -6
2 -3  7 -1
3  4 -8  9

In [17]:
df[df<0]=0

In [18]:
df

A  B  C
0  1  0  2
1  2  3  0
2  0  7  0
3  4  0  9

In [20]:
26.#Access the 3rd element from the given numpy array. 
arr = np.array([10,20,30,40,50])

In [21]:
arr[2]

30

In [22]:
27.#Retrieve the element at index(1,2) from the 2D numpy array.
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [23]:
arr_2d[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [24]:
28.#Using boolean indexing, extract elements greater than 5 from the given numpy array.
arr = np.array([3,8,2,10,5,7])

In [25]:
boolean_index = arr > 5

In [26]:
boolean_index

array([False,  True, False,  True, False,  True])

In [27]:
29.#Perform basic slicing to extract elements from index 2 to 5(inclusive) from the given numpy array.
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])

In [28]:
arr[2:6]

array([3, 4, 5, 6])

In [29]:
30.#Slice the 2D numpy array to extract the sub-array[[2,3].[5,6]] from the given array.
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [30]:
arr_2d[0:2,[1,2]]

array([[2, 3],
       [5, 6]])

In [34]:
36.#Given an array arr of shape(3,3),add a scalar value of 5 to each element using numpy broadcasting.
import numpy as np
arr = np.array([[5,6,7],
               [3,5,1],
               [4,1,2]])
scalar = 5
res = arr+scalar

In [35]:
res

array([[10, 11, 12],
       [ 8, 10,  6],
       [ 9,  6,  7]])

In [33]:
37.#Consider two arraya arr1 of shape(1,3) and arr2 of shape(3,4).Multiplyeach row of arr2 by the corresponding element in arr1 using numpy broadcasting.
arr1 = np.array([3,5,7])
arr2 = np.array([[2,3,4,5],
                [1,4,6,7],
                [6,8,9,0]])
result = arr2*arr1

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [36]:
38.#Given a 1D array arr1 of shape(1,4) and a 2D array arr2 of shape(4,3) add arr1 to each row of arr2 using numpy broadcasting.
import numpy as np
arr1 = np.array([2,3,4,5])
arr2 = np.array([[4,5,6],
                 [3,2,6],
                 [1,6,8],
                 [5,8,9]])
add = arr1+arr2

ValueError: operands could not be broadcast together with shapes (4,) (4,3) 

In [39]:
41.#Calculate column_wise mean for the given array.
arr = np.array([[1,2,3],[4,5,6]])
arr.mean(axis =0)

array([2.5, 3.5, 4.5])

In [40]:
42.#Find maximum value in each row of the given array.
arr = np.array([[1,2,3],[4,5,6]])
np.max(arr,1)

array([3, 6])

In [46]:
43.#For the given array, find indices of maximum value in each column.
arr = np.array([[1,2,3],[4,5,6]])
np.max(arr,0)

array([4, 5, 6])